version: '3'
services:
    dbx-webhook:
        container_name: dbx-webhook
        build: .
        restart: always
        ports:
            - "5050:5050"
        env_file:
            - ./.env
        stdin_open: true
        tty: true
